services:
    db:
        container_name: zitkino_db
        build:
            context: .docker/mysql
        ports:
            - "3306:3306"
        volumes:
            - ./.docker/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: heslo
            MYSQL_DATABASE: zitkino
            MYSQL_PASSWORD: heslo

    www:
        container_name: zitkino_www
        build:
            context: .docker/php
        depends_on:
            - db
        links:
            - db
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
            - ./.docker/php/apache.conf:/etc/apache2/sites-enabled/000-default.conf
            - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
