# These lines define a route using YAML configuration. The controller used by
# the route (FrameworkBundle:Template:template) is a convenient shortcut when
# the template can be rendered without executing any logic in your own controller.
# See https://symfony.com/doc/current/templates.html#rendering-a-template-directly-from-a-route
#homepage:
#    path: /
#    controller: App\Controllers\HomeController::index
#    defaults:
##        template: default/homepage.html.twig
#        _locale: cs
#    requirements:
#        _locale: cs
        
database_slug_routes:
    resource: .
    type: database_slug

controllers:
    resource:
        path: '../src/Controllers/'
        namespace: App\Controllers
    type: attribute
#    prefix: /
#    condition: "'%app.locale%' != 'cs'"
    defaults:
        _locale: cs
#    requirements:
#        _locale: en|cs
