# These lines define a route using YAML configuration. The controller used by
# the route (FrameworkBundle:Template:template) is a convenient shortcut when
# the template can be rendered without executing any logic in your own controller.
# See https://symfony.com/doc/current/templates.html#rendering-a-template-directly-from-a-route
controllers:
    resource:
        path: '../src/Controllers/'
        namespace: App\Controllers
    type: attribute
    prefix:
        cs: '/cs' # don't prefix URLs for the default locale
        en: '/en'
    defaults:
        _locale: '%app.locale%'
